<template>
  <div class="future-bar-box">
    <div class="fb-bar">
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE •
    </div>
    <div class="fb-bar bar2">
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE • FUTURE •
      FUTURE • FUTURE •
    </div>
  </div>
</template>

<script setup></script>

<style scoped>
.future-bar-box {
  width: calc(100%);
  overflow: hidden;
  /* border: 1px solid salmon; */

  text-transform: uppercase;
  background: url("~/assets/greyy.png") 0 0 / cover no-repeat;
  color: #de466c;
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}

.fb-bar {
  font-weight: bold;
  text-wrap-mode: nowrap;
  animation: marquee-vertical 40s linear infinite ;
}

.bar2 {
  animation: marquee-vertical2 40s linear infinite ;

}

@keyframes marquee-vertical {
  0% {
    transform: translateX(0%);
  }
  100% {
    transform: translateX(-100%);
  }
}


@keyframes marquee-vertical2 {
  0% {

    transform: translate(0%) scaleX(-1);
  }
  100% {

    transform: translate(100%)  scaleX(-1);
  }
}

</style>
